### ISSUE TITLE
hide event not namespaced

### ISSUE THREAD

**Issue by TanyaSemler** [eternicode/bootstrap-datepicker#1268]
When hiding the date picker, the event isn't namespaced and is caught by other event handlers. A custom event like hide ought to be namespaced I think?

In my case, I have a listener on a panel with hide.bs.collapsible, which is triggered when a field inside is used with the date-picker. I have solved it in my end by testing on the event namespace, but shouldn't it be the other way around?

**Comment by acrobat** [comment]
Yes that's an issue we are aware of and have a [few issues and PR related to this](https://github.com/eternicode/bootstrap-datepicker/labels/namespaced%20events) and we are working on a way to fix this. But most likely it will be fixed in a major version (2.0) as this would mean a BC break. 

Thanks for the report but check the issues in the link above for the progress on it. Closing this for now!
