### ISSUE TITLE
Downloading zip gives me v1.5.0-dev

### ISSUE THREAD

**Issue by KrunchMuffin** [eternicode/bootstrap-datepicker#1332]
Shouldn't the zip download be the master?

**Comment by acrobat** [comment]
Master is currently 1.5.0-dev version and the latest stable release is 1.4.0. What zip download do you mean?

**Comment by KrunchMuffin** [comment]
on the main page https://github.com/eternicode/bootstrap-datepicker right column.

**Comment by KrunchMuffin** [comment]
even if i right to the file in dist folder, it says 1.5-dev at top, but the bottom says 1.4.1-dev
https://raw.githubusercontent.com/eternicode/bootstrap-datepicker/master/dist/js/bootstrap-datepicker.js

**Comment by acrobat** [comment]
The link on the right should and downloads master. Master is the current development branch for the next feature release (1.5.0), but indeed the version of the datepicker object is wrong on master (wring merge from the 1.4 branch) and i will correct that tomorrow morning!

**Comment by KrunchMuffin** [comment]
Yes, it should download the master but the master should never be your development branch, it should be the stable version. That's why the download of the master branch is so prominent. People come looking for your project and want to download the most current stable version and they expect that to be the master and that's why the download link is there.
>The main branch of a repository is usually named master, and represents a relatively stable version of the project you're working on.
https://help.github.com/articles/branching-out/

But I digress. It's your repo you can use it as you like, but would probably good to let people know.

**Comment by korun** [comment]
We could add `Download latest stable zip` link in README, hmm?

**Comment by acrobat** [comment]
@KrunchMuffin that's just the type of gitflow you choose to work with. The way we have setup our branches they are always releasable (because of the unit tests that are run each pr, commit,...). So you could still download master if you want a development version to try some new things. 

Our model here is based on the model how ex. symfony organizes their code base. Master is the base for the next feature release and the specific version branches (in our case 1.4) are bugfix development branches. 
That way we can develop multiple bugfix releases and a feature release in the same time. So if you want the latest development code you can download a zip of the matser of version branch. If you require a stable version you can download (or require the lib with bower, composer, etc) a release zip. You can find those releases [here ](https://github.com/eternicode/bootstrap-datepicker/releases)

@korun It's indeed maybe a good idea to include a link to the latest stable or to the release page. And as an extra we could add some info about how our gitflow works, that way we can prevent some misunderstandings in the future!

**Comment by KrunchMuffin** [comment]
THanks
