### ISSUE TITLE
Update method deleting date

### ISSUE THREAD

**Issue by KrunchMuffin** [eternicode/bootstrap-datepicker#1635]
If I setup the datepicker to not allow dates previous to  today, but I load a form with a pre-loaded date that is previous to today and run the update method, the date gets removed.

**Comment by KrunchMuffin** [comment]
damn it, i can't replicate it
http://jsfiddle.net/fv9m5my0/13/
but, if you do select the datepicker and just click off of it, the date disappears

**Comment by KrunchMuffin** [comment]
ok, so I did my own investigating since this is not getting traction.

this appears to happen when I don't allow dates in the past to be selected, but the value coming from the db is in the past.

in this line, in my case, `formatted` is returning blank so the val get wiped
https://github.com/eternicode/bootstrap-datepicker/blob/master/dist/js/bootstrap-datepicker.js#L609

for now all i did was check if formatted is blank and if so, leave the val untouched.

**Comment by frederikprijck** [comment]
Isn't this what you expect to happen?

You create a datepicker with certain date boundaries, yet you want the datepicker to show a date which is outside of these boundaries ? That's somewhat odd.

The reason your date gets removed when clicking outside of the textbox or calling update is because the date is not allowed to be used inside the datepicker, since that's what you explicitly told the datepicker to do: do not allow dates < today.

If you do want to achieve this, I'd advice to remove the datepicker date boundaries and go with a simple jquery custom validation to ensure validation of the date to be > today. In this case, the datepicker will still allow values < today, but the form will be invalid.

**Comment by KrunchMuffin** [comment]
ok
